name: Update Dockerfiles
on:
  workflow_dispatch:
  repository_dispatch:
    types: [update_dockerfiles]
  push:
    paths:
      - 'cicd/ubuntu/**'


jobs:
  base:
    name: Building ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: 
          - name: Ubuntu Base Dockerfile
            file: ./cicd/ubuntu/base.Dockerfile
            tag: base
            context: cicd/ubuntu/
    env:
      APP_NAME_BASE: "blazium"  # Define a global base app name
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.file }}
          context: ${{ matrix.context }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME_BASE }}-${{ matrix.tag }}:latest

  docker:
    name: Building ${{ matrix.name }}
    needs: base
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: 
          - name: Ubuntu Linux Dockerfile (Windows/Linux/Android)
            file: ./cicd/ubuntu/linux.Dockerfile
            tag: linux
            context: cicd/ubuntu/
          - name: Ubuntu Apple Dockerfile (MacOS/iOS)
            file: ./cicd/ubuntu/apple.Dockerfile
            tag: apple
            context: cicd/ubuntu/
          # - name: Web Dockerfile
          #   file: ./images/web.Dockerfile
          #   tag: web
          # - name: Android Dockerfile
          #   file: ./images/android.Dockerfile
          #   tag: android
          # - name: Windows Dockerfile
          #   file: ./images/windows.Dockerfile
          #   tag: windows
    env:
      APP_NAME_BASE: "blazium"  # Define a global base app name
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.file }}
          context: ${{ matrix.context }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME_BASE }}-${{ matrix.tag }}:latest
