name: Testing
on:
  workflow_dispatch:

env:
  BASE_FOLDER: deps
  XCODE_VERSION: "15.4"

jobs:
  testing:
    name: Testing
    runs-on: "macos-latest"
    steps:
      - name: Set up Base Folder
        run: mkdir -p "$(pwd)/$BASE_FOLDER"

      - name: List SDKs and Developer Platforms
        run: |
          ls -la /Applications/ >> $GITHUB_STEP_SUMMARY
          ls -la /Applications/Xcode_$XCODE_VERSION.app/Contents/Developer/Platforms/ >> $GITHUB_STEP_SUMMARY
          ls -la /Applications/Xcode_$XCODE_VERSION.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs >> $GITHUB_STEP_SUMMARY
          ls -la /Applications/Xcode_$XCODE_VERSION.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs >> $GITHUB_STEP_SUMMARY
          ls -la /Applications/Xcode_$XCODE_VERSION.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs >> $GITHUB_STEP_SUMMARY

      - name: Create tar.xz archives for iPhoneOS directories
        run: |
          SDK_PATH="/Applications/Xcode_$XCODE_VERSION.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs"
          for sdk in $(ls "$SDK_PATH" | grep iPhoneOS | grep -v iPhoneOS.sdk); do
            sudo tar -cJvhf "$(pwd)/$BASE_FOLDER/${sdk}.tar.xz" "$SDK_PATH/$sdk"
          done

      - name: Create tar.xz archives for iPhoneSimulator directories
        run: |
          SDK_PATH="/Applications/Xcode_$XCODE_VERSION.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs"
          for sdk in $(ls "$SDK_PATH" | grep iPhoneSimulator | grep -v iPhoneSimulator.sdk); do
            sudo tar -cJvhf "$(pwd)/$BASE_FOLDER/${sdk}.tar.xz" "$SDK_PATH/$sdk"
          done

      - name: Create tar.xz archives for MacOSX directories
        run: |
          SDK_PATH="/Applications/Xcode_$XCODE_VERSION.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs"
          for sdk in $(ls "$SDK_PATH" | grep MacOSX | grep -v MacOSX.sdk); do
            sudo tar -cJvhf "$(pwd)/$BASE_FOLDER/${sdk}.tar.xz" "$SDK_PATH/$sdk"
          done

      - name: List Base Folder Contents and Add to Summary
        run: |
          ls -la "$(pwd)/$BASE_FOLDER" >> $GITHUB_STEP_SUMMARY
