name: Testing
on:
  workflow_dispatch:

jobs:
  testing:
    name: Testing
    runs-on: "macos-latest"
    steps:
      - run: |
          ls -la /Applications/ >> $GITHUB_STEP_SUMMARY
          ls -la /Applications/Xcode_15.4.app/Contents/Developer/Platforms/ >> $GITHUB_STEP_SUMMARY
          ls -la /Applications/Xcode_15.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs >> $GITHUB_STEP_SUMMARY
          ls -la /Applications/Xcode_15.4.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs >> $GITHUB_STEP_SUMMARY
          ls -la /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs >> $GITHUB_STEP_SUMMARY

