name: 🔗 GHA
on:
  repository_dispatch:
    types: [trigger_build]

concurrency:
  group: ci-${{github.actor}}-nightly-runner
  cancel-in-progress: true

jobs:

  static-checks:
    name: 📊 Static checks
    uses: ./.github/workflows/static_checks.yml

  android-build:
    name: 🤖 Android
    needs: static-checks
    uses: ./.github/workflows/android_builds.yml

  web-build:
    name: 🌐 Web
    needs: static-checks
    uses: ./.github/workflows/web_builds.yml

  ios-build:
    name: 🍏 iOS
    needs: [static-checks, android-build, web-build]
    uses: ./.github/workflows/ios_builds.yml

  linux-build:
    name: 🐧 Linux
    needs: [static-checks, android-build, web-build]
    uses: ./.github/workflows/linux_builds.yml

  macos-build:
    name: 🍎 macOS
    needs: [static-checks, android-build, web-build]
    uses: ./.github/workflows/macos_builds.yml

  windows-build:
    name: 🏁 Windows
    needs: [static-checks, android-build, web-build]
    uses: ./.github/workflows/windows_builds.yml
