name: Template Deploy
on:
  workflow_call:
    inputs:
      build_sha:
        description: "Build commit SHA to use for this job"
        required: true
        type: string
      runner_id:
        description: "Runner ID of the Parent Runner"
        required: true
        type: string
# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: blazium-dev

concurrency:
  group: ci-${{github.actor}}-${{ github.event.client_payload.type || 'nightly' }}-template-deploy
  cancel-in-progress: true

jobs:
  build-monoglue:
    runs-on: "ubuntu-20.04"
    name: Example for Template Deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: blazium-engine/ci_cd
          submodules: recursive

      # - name: Download No. 1 File
      #   id: download-1
      #   uses: ./.github/actions/cerebro-download-build
      #   with:
      #     name: linux-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
      #     run_id: ${{ inputs.runner_id }}
      #     cerebro_url: ${{ secrets.CEREBRO_URL }}
      #     cerebro_auth: ${{ secrets.BLAZIUM_AUTH }}
      #     folder: ${{ github.workspace }}/downloads

      - name: Download All Template Files
        uses: ./.github/actions/cerebro-download-multi-build
        with:
          names: |
            linux-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-debug-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-debug-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-debug-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-debug-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
            web-template-${{ github.event.client_payload.type || 'nightly' }}
            web-nothreads-template-${{ github.event.client_payload.type || 'nightly' }}
            web-debug-template-${{ github.event.client_payload.type || 'nightly' }}
            web-nothreads-debug-template-${{ github.event.client_payload.type || 'nightly' }}
            web-dlink-template-${{ github.event.client_payload.type || 'nightly' }}
            web-nothreads-dlink-template-${{ github.event.client_payload.type || 'nightly' }}
            web-dlink-debug-template-${{ github.event.client_payload.type || 'nightly' }}
            web-nothreads-dlink-debug-template-${{ github.event.client_payload.type || 'nightly' }}
          run_id: ${{ inputs.runner_id }}
          cerebro_url: ${{ secrets.CEREBRO_URL }}
          cerebro_auth: ${{ secrets.BLAZIUM_AUTH }}
          folder: ${{ github.workspace }}/downloads

      - name: Uncompress Templates
        uses: ./.github/actions/multi-uncompress-tar-gz
        with:
          names: |
            linux-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-debug-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-debug-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-debug-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-debug-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
            web-template-${{ github.event.client_payload.type || 'nightly' }}
            web-nothreads-template-${{ github.event.client_payload.type || 'nightly' }}
            web-debug-template-${{ github.event.client_payload.type || 'nightly' }}
            web-nothreads-debug-template-${{ github.event.client_payload.type || 'nightly' }}
            web-dlink-template-${{ github.event.client_payload.type || 'nightly' }}
            web-nothreads-dlink-template-${{ github.event.client_payload.type || 'nightly' }}
            web-dlink-debug-template-${{ github.event.client_payload.type || 'nightly' }}
            web-nothreads-dlink-debug-template-${{ github.event.client_payload.type || 'nightly' }}
          input_dir: ${{ github.workspace }}/downloads
          output_dir: ${{ github.workspace }}/extracted

      - name: Copy & Rename Windows Templates
        uses: ./.github/actions/multi-copy-rename
        with:
          names: |
            windows-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-debug-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-debug-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-debug-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-debug-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
          filename_old: |
            blazium.windows.template_release.x86_64.exe
            blazium.windows.template_debug.x86_64.exe
            blazium.windows.template_release.x86_32.exe
            blazium.windows.template_debug.x86_32.exe
            blazium.windows.template_release.x86_64.console.exe
            blazium.windows.template_debug.x86_64.console.exe
            blazium.windows.template_release.x86_32.console.exe
            blazium.windows.template_debug.x86_32.console.exe
          filename_new: |
            windows_release_x86_64.exe
            windows_debug_x86_64.exe
            windows_release_x86_32.exe
            windows_debug_x86_32.exe
            windows_release_x86_64_console.exe
            windows_debug_x86_64_console.exe
            windows_release_x86_32_console.exe
            windows_debug_x86_32_console.exe
          input_dir: ${{ github.workspace }}/extracted
          output_dir: ${{ github.workspace }}/templates

      - name: Copy & Rename Windows Templates (mono)
        uses: ./.github/actions/multi-copy-rename
        with:
          names: |
            windows-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-debug-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-debug-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-debug-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
            windows-debug-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
          filename_old: |
            blazium.windows.template_release.x86_64.mono.exe
            blazium.windows.template_debug.x86_64.mono.exe
            blazium.windows.template_release.x86_32.mono.exe
            blazium.windows.template_debug.x86_32.mono.exe
            blazium.windows.template_release.x86_64.mono.console.exe
            blazium.windows.template_debug.x86_64.mono.console.exe
            blazium.windows.template_release.x86_32.mono.console.exe
            blazium.windows.template_debug.x86_32.mono.console.exe
          filename_new: |
            windows_release_x86_64.exe
            windows_debug_x86_64.exe
            windows_release_x86_32.exe
            windows_debug_x86_32.exe
            windows_release_x86_64_console.exe
            windows_debug_x86_64_console.exe
            windows_release_x86_32_console.exe
            windows_debug_x86_32_console.exe
          input_dir: ${{ github.workspace }}/extracted
          output_dir: ${{ github.workspace }}/templates/mono

      - name: Copy & Rename Linux Templates
        uses: ./.github/actions/multi-copy-rename
        with:
          names: |
            linux-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
          filename_old: |
            blazium.linuxbsd.template_release.x86_64
            blazium.linuxbsd.template_debug.x86_64
            blazium.linuxbsd.template_release.x86_32
            blazium.linuxbsd.template_debug.x86_32
          filename_new: |
            linux_release.x86_64
            linux_debug.x86_64
            linux_release.x86_32
            linux_debug.x86_32
          input_dir: ${{ github.workspace }}/extracted
          output_dir: ${{ github.workspace }}/templates

      - name: Copy & Rename Linux Templates (mono)
        uses: ./.github/actions/multi-copy-rename
        with:
          names: |
            linux-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
          filename_old: |
            blazium.linuxbsd.template_release.x86_64.mono
            blazium.linuxbsd.template_debug.x86_64.mono
            blazium.linuxbsd.template_release.x86_32.mono
            blazium.linuxbsd.template_debug.x86_32.mono
          filename_new: |
            linux_release.x86_64
            linux_debug.x86_64
            linux_release.x86_32
            linux_debug.x86_32
          input_dir: ${{ github.workspace }}/extracted
          output_dir: ${{ github.workspace }}/templates/mono

      - name: List Templates Directory
        shell: bash
        run: |
          if [ -d "${GITHUB_WORKSPACE}/templates" ]; then
            echo "Contents of the templates directory:" >> $GITHUB_STEP_SUMMARY
            echo "$(ls -la "${GITHUB_WORKSPACE}/templates")" >> $GITHUB_STEP_SUMMARY
          else
            echo "Directory ${GITHUB_WORKSPACE}/templates does not exist." >> $GITHUB_STEP_SUMMARY
          fi

      - name: List Templates/Mono Directory
        shell: bash
        run: |
          if [ -d "${GITHUB_WORKSPACE}/templates/mono" ]; then
            echo "Contents of the templates/mono directory:" >> $GITHUB_STEP_SUMMARY
            echo "$(ls -la "${GITHUB_WORKSPACE}/templates/mono")" >> $GITHUB_STEP_SUMMARY
          else
            echo "Directory ${GITHUB_WORKSPACE}/templates/mono does not exist." >> $GITHUB_STEP_SUMMARY
          fi
      # - name: Uncompress File
      #   id: new-folder
      #   uses: ./.github/actions/uncompress-tar-gz
      #   with:
      #     file_path: ${{ steps.download-1.outputs.file_path }}
      #     output_dir: ${{ github.workspace }}/extracted

      # - name: Update File
      #   shell: bash
      #   run: |
      #     # Extract file path from the previous step
      #     CUR_FOLDER="${{ steps.new-folder.outputs.target_folder }}"
      #     NEW_FOLDER="${{ github.workspace }}/templates"
      #     CUR_FILE="blazium.linuxbsd.template_release.x86_64"
      #     NEW_FILE="linux_release.x86_64"

      #     mkdir -r $NEW_FOLDER
      #     cp $CUR_FOLDER/$CUR_FILE $NEW_FOLDER/$NEW_FILE
