name: Template Deploy
on:
  workflow_call:
    inputs:
      build_sha:
        description: "Build commit SHA to use for this job"
        required: true
        type: string
      runner_id:
        description: "Runner ID of the Parent Runner"
        required: true
        type: string
# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: blazium-dev

concurrency:
  group: ci-${{github.actor}}-${{ github.event.client_payload.type || 'nightly' }}-template-deploy
  cancel-in-progress: true

jobs:
  build-monoglue:
    runs-on: "ubuntu-20.04"
    name: Example for Template Deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: blazium-engine/ci_cd
          submodules: recursive

      # - name: Download No. 1 File
      #   id: download-1
      #   uses: ./.github/actions/cerebro-download-build
      #   with:
      #     name: linux-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
      #     run_id: ${{ inputs.runner_id }}
      #     cerebro_url: ${{ secrets.CEREBRO_URL }}
      #     cerebro_auth: ${{ secrets.BLAZIUM_AUTH }}
      #     folder: ${{ github.workspace }}/downloads

      - name: Download All Linux Template Files
        id: download-1
        uses: ./.github/actions/cerebro-download-multi-build
        with:
          names: |
            linux-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
          run_id: ${{ inputs.runner_id }}
          cerebro_url: ${{ secrets.CEREBRO_URL }}
          cerebro_auth: ${{ secrets.BLAZIUM_AUTH }}
          folder: ${{ github.workspace }}/downloads

      - name: Uncompress File
        id: new-folder
        uses: ./.github/actions/multi-uncompress-tar-gz
        with:
          names: |
            linux-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-mono-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-64bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-mono-32bit-${{ github.event.client_payload.type || 'nightly' }}
            linux-debug-template-32bit-${{ github.event.client_payload.type || 'nightly' }}
          input_dir: ${{ github.workspace }}/downloads
          output_dir: ${{ github.workspace }}/extracted

      # - name: Uncompress File
      #   id: new-folder
      #   uses: ./.github/actions/uncompress-tar-gz
      #   with:
      #     file_path: ${{ steps.download-1.outputs.file_path }}
      #     output_dir: ${{ github.workspace }}/extracted

      # - name: Update File
      #   shell: bash
      #   run: |
      #     # Extract file path from the previous step
      #     CUR_FOLDER="${{ steps.new-folder.outputs.target_folder }}"
      #     NEW_FOLDER="${{ github.workspace }}/templates"
      #     CUR_FILE="blazium.linuxbsd.template_release.x86_64"
      #     NEW_FILE="linux_release.x86_64"

      #     mkdir -r $NEW_FOLDER
      #     cp $CUR_FOLDER/$CUR_FILE $NEW_FOLDER/$NEW_FILE
