name: 🌐 Web Builds
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: blazium-dev
  SCONSFLAGS: verbose=yes warnings=extra werror=yes debug_symbols=no use_closure_compiler=yes
  EM_VERSION: 3.1.64
  EM_CACHE_FOLDER: "emsdk-cache"

concurrency:
  group: ci-${{github.actor}}-${{ github.event.client_payload.type || 'nightly' }}-web
  cancel-in-progress: true

jobs:
  web-template:
    runs-on: "ubuntu-22.04"
    name: ${{ matrix.name }}
    strategy:
      max-parallel: 3
      fail-fast: true
      matrix:
        include:

          - name: Editor (target=editor)
            cache-name: web-editor
            target: editor
            sconsflags: ${{ github.event.client_payload.production && 'production=yes' || '' }}
            tests: false
            artifact: true

          - name: Template w/ threads (target=template_release, threads=yes)
            cache-name: web-template
            target: template_release
            sconsflags: threads=yes ${{ github.event.client_payload.production && 'production=yes' || 'dev_build=yes' }}
            tests: false
            artifact: true

          - name: Template w/o threads (target=template_release, threads=no)
            cache-name: web-nothreads-template
            target: template_release
            sconsflags: threads=no ${{ github.event.client_payload.production && 'production=yes' || 'dev_build=yes' }}
            tests: false
            artifact: true

          - name: Template w/ threads (target=template_debug, threads=yes)
            cache-name: web-debug-template
            target: template_debug
            sconsflags: threads=yes ${{ github.event.client_payload.production && 'production=yes' || 'dev_build=yes' }}
            tests: false
            artifact: true

          - name: Template w/o threads (target=template_debug, threads=no)
            cache-name: web-nothreads-debug-template
            target: template_debug
            sconsflags: threads=no ${{ github.event.client_payload.production && 'production=yes' || 'dev_build=yes' }}
            tests: false
            artifact: true

          - name: Template w/ threads (target=template_release, dlink_enabled=yes, threads=yes)
            cache-name: web-dlink-template
            target: template_release
            sconsflags: threads=yes dlink_enabled=yes ${{ github.event.client_payload.production && 'production=yes' || 'dev_build=yes' }}
            tests: false
            artifact: true

          - name: Template w/o threads (target=template_release, dlink_enabled=yes, threads=no)
            cache-name: web-nothreads-dlink-template
            target: template_release
            sconsflags: threads=no dlink_enabled=yes ${{ github.event.client_payload.production && 'production=yes' || 'dev_build=yes' }}
            tests: false
            artifact: true

          - name: Template w/ threads (target=template_debug, dlink_enabled=yes, threads=yes)
            cache-name: web-dlink-debug-template
            target: template_debug
            sconsflags: threads=yes dlink_enabled=yes ${{ github.event.client_payload.production && 'production=yes' || 'dev_build=yes' }}
            tests: false
            artifact: true

          - name: Template w/o threads (target=template_debug, dlink_enabled=yes, threads=no)
            cache-name: web-nothreads-dlink-debug-template
            target: template_debug
            sconsflags: threads=no dlink_enabled=yes ${{ github.event.client_payload.production && 'production=yes' || 'dev_build=yes' }}
            tests: false
            artifact: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: blazium-engine/blazium
          ref: ${{ github.event.client_payload.branch || env.GODOT_BASE_BRANCH }}
          submodules: recursive
          fetch-depth: 2

      - name: Set up Emscripten latest
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
          cache-key: emsdk-${{ matrix.cache-name }}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}

      - name: Verify Emscripten setup
        run: |
          emcc -v

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          platform: web
          target: ${{ matrix.target }}
          tests: ${{ matrix.tests }}

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}

      - name: Create ZIP Archive
        run: |
          zip -r ${{ matrix.cache-name }}-${{ github.event.client_payload.type || 'nightly' }}.zip ./bin

      - uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_ACCESS_KEY }}
          secret_key: ${{ secrets.DO_SECRET_KEY }}
          space_name: ${{ secrets.DO_SPACE_NAME }}
          space_region: ${{ secrets.DO_SPACE_REGION }}
          source: ${{ matrix.cache-name }}-${{ github.event.client_payload.type || 'nightly' }}.zip
          out_dir: web-editor/${{ github.event.client_payload.type || 'nightly' }}${{ startsWith(matrix.target, 'template_') && '/template' || '' }}

  deploy:
    name: Deploying Web Editor to ${{ github.event.client_payload.type || 'nightly' }}
    runs-on: ubuntu-latest
    if: contains('nightly prerelease release', github.event.client_payload.type)
    env:
      APP_NAME_BASE: "blazium_web-editor"  # Define a global base app name
      CDN_URL: "https://cdn.blazium.app/"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download and extract web editor package
        run: |
          mkdir -p storage
          curl -L "${{ env.CDN_URL }}web-editor/${{ github.event.client_payload.type || 'nightly' }}/web-editor-${{ github.event.client_payload.type || 'nightly' }}.zip" -o storage/web-editor.zip
          unzip storage/web-editor.zip -d storage
          inner_zip=$(find storage -type f -name 'blazium.web.editor.*.zip' | head -n 1)
          mkdir -p ./web-editor/static
          unzip "$inner_zip" -d ./web-editor/static
          mv ./web-editor/static/blazium.editor.html ./web-editor/static/index.html

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./web-editor/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME_BASE }}-${{ github.event.client_payload.type || 'nightly' }}:latest
